FROM cmcg/bamboo-node-ngsw:%VERSION%
LABEL org.opencontainers.image.authors="cmcgroarty@idesignconsulting.com"

USER root:root

RUN npm install -g firebase-tools@^13 fireway@^1

RUN rm -rf /tmp/* \
&& node -p process.versions \
&& node -p 'module.paths'

RUN chown -R $USERNAME:$USERNAME $HOME/.npm

USER $USERNAME:$USERNAME
